### PR TITLE
fixed Compilation and fixed for the gm commands

### PR DESCRIPTION
**Pull request by chris-hill1990**
Fixed Compilation and fixed for the gm commands that allowed you to escape detention

### CODE REVIEW

**Comment by Groudonmaster** [comment]
I’m impressed at the PR that gets made after 2 years since the last activity

**Comment by Rotem12** [comment]
Hey, the fixes to make sure this compiles on newer BYOND version are ok but as far as GM commands go, there's no issue with GMs escaping detention.

**Comment by chris-hill1990** [comment]
@Rotem12 I can pull out those fixes no problem if you like

**Comment by LuckySara** [comment]
> Hey, the fixes to make sure this compiles on newer BYOND version are ok but as far as GM commands go, there's no issue with GMs escaping detention.

You should tell that to Rafi, Rotem. In his server, he made sure Staff couldn't escape at all. lol

**Comment by chris-hill1990** [comment]
It alright i pulled the changes out no problem i can put them back if it decided that we want them or address it in another pr i don't mind either way

**Pull request merged**
