### PR TITLE
fixed charms classroom board was bug

### PR DESCRIPTION
**Pull request by chris-hill1990**
Charms black board thought it belonged to headmaster class west classroom stopping players from joining for a charms class using the board

### CODE REVIEW

**Comment by Rotem12** [comment]
Ok so, the class is classified based on the spell that's randomly picked and not really based on anything on the map.

**Comment by chris-hill1990** [comment]
However when you click on the board to start a class it thought the board
belonged to a different class than where the people clicking the board were

**Comment by Rotem12** [comment]
I can't review map changes so please describe to me what you did and I'll approve based on that

**Comment by chris-hill1990** [comment]
charms
basically the area in the red box i set to charms area

**Pull request merged**
